apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: netlifytrial-urpw
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: netlifytrial-urpw
    app.kubernetes.io/part-of: netlifytrial-122
  name: netlifytrial-urpwv2rg
spec:
  path: /
  port:
    targetPort: 3001
  to:
    kind: Service
    name: netlifytrial-urpw
    weight: null
status: {}
