apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: netlifytrial-urpw
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: netlifytrial-urpw
    app.kubernetes.io/part-of: netlifytrial-122
  name: netlifytrial-urpw
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: netlifytrial-urpw
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: netlifytrial-urpw
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/pshivpuj-tenant/netlifytrial-122/netlifytrial-urpw@sha256:f81ddecfa9eda4018136ede31e30280fe7d217e07500a5dcbe9fe14caf01f63f
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
