apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: netlifytrial-urpw
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: netlifytrial-urpw
    app.kubernetes.io/part-of: netlifytrial-122
  name: netlifytrial-urpw
spec:
  ports:
  - name: "3001"
    port: 3001
    targetPort: 3001
  selector:
    app.kubernetes.io/instance: netlifytrial-urpw
status:
  loadBalancer: {}
